services:
  - type: web
    name: xfiles
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: xfiles-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: xfiles-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: xfiles-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: xfiles-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: xfiles-db
          property: password

databases:
  - name: xfiles-db
    databaseName: xfiles
    user: xfiles
    plan: free
